name: fit2json
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Stefan Stammberger <some.fusion@gmail.com>

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  glob: ^1.2.0
  fit_parser:
    git:
      url: https://github.com/fusion44/fit_parser.git
      ref: json
  json_annotation: ^3.0.1
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.9.0
  json_serializable: ^3.4.0
